// Customer-side mock data matching the production API response shape.
export const customerMockResponse = {
  services: [
    {
      id: "341",
      name: "Royal Wedding Palace",
      description:
        "An exquisite heritage palace turned wedding venue, featuring grand ballrooms and lush gardens — perfect for unforgettable celebrations.",
      images: [
        "https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1600",
        "https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?w=1600",
        "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600",
      ],
      area: "Amer Fort Road",
      city: "Jaipur",
      state: "Rajasthan",
      add_line1: "Heritage Lane, Plot 12",
      add_line2: null,
      country: "India",
      pincode: "302002",
      latitude: 26.98,
      longitude: 75.85,
      vendor_name: "John's Business",
      vendor_id: "1",
      vendor: {
        business_name: "John's Business",
        phone: "+91 98765 43210",
        email: "hello@johns.in",
        city: "Jaipur",
        state: "Rajasthan",
        country: "India",
        experience: 12,
      },
      service_type: "venue",
      venue: {
        venue_type: "Banquet Hall",
        venue_nature: "Indoor",
        max_capacity: 800,
        min_capacity: 100,
        square_feet: 12000.0,
        parking_capacity: 350,
        venue_policies: {
          alcohol_policy: "not-allowed",
          catering_policy: "allowed",
          decoration_policy: "allowed",
          other_policies: [
            { title: "Music", description: "Not allowed after 12 AM" },
            { title: "Outside DJ", description: "Allowed with prior approval" },
          ],
        },
      },
      variants: [
        {
          id: 748,
          variant_name: "Standard Day Rental",
          pricing_type: "BASE_PRICE",
          currency: "INR",
          pricing: { veg_price: 550, pricing_mode: "per_plate", non_veg_price: 760 },
          inclusions: ["Hall booking", "Basic lighting", "Sound system"],
          exclusions: [],
          is_default: true,
        },
        {
          id: 749,
          variant_name: "Premium Package",
          pricing_type: "BASE_PRICE",
          currency: "INR",
          pricing: { pricing_mode: "rental", rental_price: 125000 },
          inclusions: ["Premium decor", "Lighting", "Sound", "Bridal suite"],
          exclusions: [],
          is_default: false,
        },
      ],
      tags: ["Heritage", "Outdoor garden", "Premium"],
      amenities: ["parking", "wifi", "ac", "decoration", "security"],
      rating: 4.7,
      total_reviews: 128,
    },
    {
      id: "332",
      name: "Spice Route Catering",
      description:
        "Multi-cuisine catering for weddings and large events with curated menus, professional staff, and tasting sessions on request.",
      images: [
        "https://images.unsplash.com/photo-1555244162-803834f70033?w=1600",
        "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=1600",
      ],
      area: "Civil Lines",
      city: "Nagpur",
      state: "Maharashtra",
      country: "India",
      pincode: "440015",
      vendor_name: "Spice Route",
      vendor_id: "2",
      vendor: {
        business_name: "Spice Route",
        phone: "+91 99887 76655",
        email: "book@spiceroute.in",
        city: "Nagpur",
        state: "Maharashtra",
        experience: 8,
      },
      service_type: "catering",
      catering: {
        cuisine_types: ["Indian", "Chinese", "Continental"],
        meal_types: ["Lunch", "Dinner"],
        service_styles: ["plated", "buffet"],
        min_order: 50,
        max_order: 1000,
        staff_included: true,
        crockery_cutlery_included: true,
        tasting_available: true,
        special_diets_supported: ["Jain", "Vegan", "Gluten-free"],
        gst_percentage: "5.00",
        customizable_menu: true,
      },
      variants: [
        {
          id: 739,
          variant_name: "Basic Package",
          pricing_type: "per_head",
          currency: "INR",
          pricing: { veg_price: 500, non_veg_price: 700 },
          inclusions: ["Buffet setup", "Basic decor", "Service staff"],
          is_default: true,
        },
      ],
      tags: ["Multi-cuisine", "Buffet", "Live counters"],
      amenities: ["catering", "decoration"],
      rating: 4.5,
      total_reviews: 64,
    },
    {
      id: "333",
      name: "Lens & Light Studio",
      description:
        "Premium wedding photography & cinematography. Candid moments, traditional shots and beautifully edited albums delivered on time.",
      images: [
        "https://images.unsplash.com/photo-1519741497674-611481863552?w=1600",
        "https://images.unsplash.com/photo-1465495976277-4387d4b0b4c6?w=1600",
      ],
      area: "Dharampeth",
      city: "Nagpur",
      state: "Maharashtra",
      country: "India",
      pincode: "440010",
      vendor_name: "Lens & Light",
      vendor_id: "3",
      vendor: {
        business_name: "Lens & Light Studio",
        phone: "+91 90909 12345",
        email: "studio@lenslight.in",
        city: "Nagpur",
        state: "Maharashtra",
        experience: 6,
      },
      service_type: "photography",
      photography: {
        photography_types: ["wedding", "pre_wedding", "newborn"],
        videography_available: true,
        drone_shoot_available: true,
        photo_delivery_count: 500,
        video_delivery_duration_minutes: 192,
        edited_photos_included: true,
        raw_photos_provided: true,
        album_included: true,
        album_pages: 40,
        coverage_hours: "8.00",
        overtime_rate_per_hour: "2000.00",
        team_size: 4,
        second_shooter_included: true,
        editing_styles: ["traditional", "cinematic"],
        experience_years: 6,
      },
      variants: [
        {
          id: 740,
          variant_name: "Wedding Day Package",
          pricing_type: "package",
          currency: "INR",
          pricing: { base_price: 50000, price_with_video: 95000 },
          inclusions: ["1000+ edited photos", "Cinematic film", "Drone shots"],
          is_default: true,
        },
      ],
      tags: ["Candid", "Cinematic", "Drone"],
      amenities: [],
      rating: 4.8,
      total_reviews: 92,
    },
    {
      id: "334",
      name: "BeatDrop DJ Co.",
      description: "High-energy DJ services with professional sound and lighting for weddings, sangeets and corporate events.",
      images: ["https://images.unsplash.com/photo-1571266028243-d220c6a8c3a8?w=1600"],
      area: "Sadar",
      city: "Nagpur",
      state: "Maharashtra",
      country: "India",
      pincode: "440001",
      vendor_name: "BeatDrop",
      vendor_id: "4",
      vendor: { business_name: "BeatDrop DJ Co.", phone: "+91 91234 56789", email: "book@beatdrop.in", city: "Nagpur", state: "Maharashtra", experience: 5 },
      service_type: "dj",
      dj: {
        equipment_included: true,
        sound_system_watts: 5000,
        light_setup_included: true,
        mc_available: true,
        languages: ["Hindi", "English", "Punjabi"],
        max_event_duration_hours: 6,
      },
      variants: [{ id: 741, variant_name: "Standard Set (4 hrs)", pricing_type: "package", currency: "INR", pricing: { base_price: 25000 }, inclusions: ["DJ + setup", "Lights"], is_default: true }],
      tags: ["Bollywood", "EDM", "Punjabi"],
      amenities: ["dj", "music"],
      rating: 4.4,
      total_reviews: 38,
    },
    {
      id: "335",
      name: "Glow by Aisha",
      description: "Bridal & party makeup using HD and airbrush products. On-location service across the city.",
      images: ["https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=1600"],
      area: "Civil Lines",
      city: "Jaipur",
      state: "Rajasthan",
      country: "India",
      pincode: "302006",
      vendor_name: "Aisha K.",
      vendor_id: "5",
      vendor: { business_name: "Glow by Aisha", phone: "+91 90011 22334", email: "hello@glowbyaisha.in", city: "Jaipur", state: "Rajasthan", experience: 7 },
      service_type: "makeup_artist",
      makeup_artist: {
        specialties: ["Bridal", "HD", "Airbrush"],
        on_location_available: true,
        travel_included_km: 25,
        trial_available: true,
        products_used: ["MAC", "Huda Beauty", "Bobbi Brown"],
        team_size: 2,
      },
      variants: [{ id: 742, variant_name: "Bridal Package", pricing_type: "package", currency: "INR", pricing: { base_price: 18000 }, inclusions: ["Bridal makeup", "Hair styling", "Draping"], is_default: true }],
      tags: ["Bridal", "HD", "Airbrush"],
      amenities: [],
      rating: 4.9,
      total_reviews: 54,
    },
    {
      id: "336",
      name: "Celebrate Co. Event Management",
      description: "End-to-end event planning — from concept and decor to logistics and on-day coordination.",
      images: ["https://images.unsplash.com/photo-1519225421980-715cb0215aed?w=1600"],
      area: "MG Road",
      city: "Pune",
      state: "Maharashtra",
      country: "India",
      pincode: "411001",
      vendor_name: "Celebrate Co.",
      vendor_id: "6",
      vendor: { business_name: "Celebrate Co.", phone: "+91 99000 11223", email: "plan@celebrate.co.in", city: "Pune", state: "Maharashtra", experience: 10 },
      service_type: "event_management",
      event_management: {
        services_offered: ["Decor", "Coordination", "Logistics", "Vendor Management"],
        team_size: 12,
        events_handled: 220,
        coverage_cities: ["Pune", "Mumbai", "Nashik"],
      },
      variants: [{ id: 743, variant_name: "Full Wedding Coordination", pricing_type: "package", currency: "INR", pricing: { base_price: 150000 }, inclusions: ["Pre-event planning", "On-day team", "Vendor coordination"], is_default: true }],
      tags: ["Full planning", "Decor", "Coordination"],
      amenities: [],
      rating: 4.6,
      total_reviews: 71,
    },
  ],
  total_count: 6,
  user_role: "customer",
};

// Mock API
export const fetchServices = async () => {
  await new Promise((r) => setTimeout(r, 300));
  return customerMockResponse;
};

export const fetchServiceById = async (id) => {
  await new Promise((r) => setTimeout(r, 250));
  const svc = customerMockResponse.services.find((s) => String(s.id) === String(id));
  if (!svc) throw new Error("Service not found");
  return svc;
};

export const mockReviews = [
  {
    id: 1,
    overall_rating: 5,
    food_beverage_rating: 5,
    service_quality_rating: 5,
    ambiance_rating: 5,
    value_for_money_rating: 4,
    title: "Dream wedding venue",
    review_text: "Absolutely magical experience. Staff was attentive and the venue looked stunning.",
    event_type: "Wedding",
    event_date: "2025-12-12",
    created_at: "2026-01-04T10:00:00Z",
    is_verified: true,
    helpful_count: 14,
    user: { name: "Priya S." },
    photos: [],
  },
  {
    id: 2,
    overall_rating: 4,
    title: "Great service overall",
    review_text: "Well organized event. A few small hiccups but the team handled them well.",
    event_type: "Reception",
    event_date: "2025-11-02",
    created_at: "2025-12-15T08:30:00Z",
    is_verified: false,
    helpful_count: 6,
    user: { name: "Rahul M." },
  },
];
