// src/components/services/ServiceFormModal/formDataInitialState.js

export const initialFormData = {
    title: "",
    description: "",
    tags: [],
    address_line1: "",
    address_line2: "",
    area: "",
    city: "",
    state: "",
    country: "India",
    pincode: "",
    geo_point: { lat: "", lon: "" },
    category: "",
    variants: [
        {
            variant_name: "Basic Package",
            pricing_type: "BASE_PRICE",
            price: "",
            is_default: true,
            inclusions: ""
        }
    ],
    amenities: [],
    capacity_min: "",
    capacity_max: "",
    hall_type: "",
    indoor_outdoor: "",
    square_feet: "",
    parking_capacity: "",
    venue_policies: {
        decoration_policy: "",
        catering_policy: "",
        alcohol_policy: "",
        other_policies: []
    },
    cuisine_types: [],
    veg_price_per_head: "",
    nonveg_price_per_head: "",
    min_order: "",
    max_order: "",
    service_style: "",
    staff_included: false,
    crockery_cutlery_included: false,
    tasting_available: false,
    genres_supported: [],
    duration_hours: "",
    equipment: [],
    lighting_included: false,
    mc_host_available: false,
    setup_time_required: "",
    photography_types: [],
    hours_covered: "",
    photos_delivered: "",
    edited_photos_count: "",
    delivery_time_days: "",
    videography_included: false,
    drone_available: false,
    album_included: false,
    event_types: [],
    team_size: "",
    includes: [],
    package_modal: "",
    vendor_network_size: "",
    experience_years: "",
    min_budget: "",
    max_budget: "",
    languages_supported: [],
    editing_styles: [],
    makeup_types: [],
    brands_used: [],
    travel_to_client: true,
    hairstyling_included: true,
    service_styles_multi: [],
    special_diets_supported: [],
};